version: '3'
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  redis-6381:
    container_name: redis-6381
    image: redis
    ports:
      - "6381:6379"

  couchbase-server:
    container_name: couchbase
    image: couchbase:4.5.0
    volumes:
      - ./couchbase/data:/opt/couchbase/var/lib/couchbase/data
    ports:
      - '8091-8094:8091-8094'
      - '11210:11210'
